# DO NOT EDIT THIS FILE -- YETIsense auto-generated file
{% if helpers.exists('YETIsense.monit.general.enabled') and YETIsense.monit.general.enabled|default("0") == "1" %}
monit_setup="/usr/local/yetisense/scripts/YETIsense/Monit/setup.sh"
monit_enable="YES"
{% else %}
monit_enable="NO"
{% endif %}
